### ISSUE TITLE
Skins problem

### ISSUE THREAD

**Issue by Adi0003** [IS4Code/YSF#152]
![sa-mp-347](https://github.com/IS4Code/YSF/assets/158862475/3a471070-cfd4-4109-a655-61f91e985064)
Hello,
I've got weird issue after installing YSF on my server. When two players meet, messages appear as in the screenshot. Moreover, every player skin is visible as CJ. Only the player can see his own correct skin. Does anyone have an idea how to fix this?

**Comment by IS4Code** [comment]
What server version is it? If DL, are you using the DL version of YSF (and not if it isn't)?

**Comment by IS4Code** [comment]
Any other plugins?

**Comment by Adi0003** [comment]
Yes: crashdetect.so regex.so streamer.so sscanf.so mysql.so pawncmd.so RouteConnectorPlugin.so YSF_DL.so FCNPC-DL.so pawnraknet.so ColAndreas.so

**Comment by Adi0003** [comment]
Solved, I had incorrect 3DTryg defines.
